### ISSUE TITLE
Reloading Page / Directly Accessing Subpage produces 404

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/6-3-5-Brainwriter#4]
**Describe the bug**
If you try to directly access one of the subpages (e.g. /topics), the server responds with a 404.
The same happens, when you reload any of the subpages.

**To Reproduce**
1. Click on 'Create Quick Round'
3. Reload

**Expected behavior**
Page should reload

**Comment by MarcBollmann** [comment]
@BuchholzTim not reproducable in dev environment

**Comment by MarcBollmann** [comment]
Bug only appears in production build atm

**Comment by BuchholzTim** [comment]
The "Bug" only appears when using an optimized production-build.
`npm run-script build` & `npx serve -l PORT`

When the frontend is started by using `npm start` the issue does not appear.

**Comment by MarcBollmann** [comment]
Tryout of https://www.npmjs.com/package/connect-history-api-fallback

**Comment by BuchholzTim** [comment]
Issue-Reason explained with multiple possible solutions: https://stackoverflow.com/a/36623117
