### ISSUE TITLE
Moderator-View Timer doesn't reload

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/6-3-5-Brainwriter#54]
**Describe the bug**
The Timer in the Moderator-View stops at 0 Seconds after the first Round, without progressing into the next timer. 

This does NOT happen always. It happened for me several times today. Too often to ignore it.

**To Reproduce**
1. Create a new Round
2. Open one or more new Tabs, to join the Round
3. Start the Round
4. Wait until the first Round is over
5. The players will now be on the "Round will continue soon"-page
6. Moderator will see this:

![image](https://user-images.githubusercontent.com/25686940/84430188-96b06280-ac29-11ea-8196-e7d867f6d06c.png)

**Expected behavior**
Timer should continue for Moderator.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Comment by GeiserRafael** [comment]
It's not reproduceable so the ticket will be closed first
