### ISSUE TITLE
It's possible to join inactive Rounds

### ISSUE THREAD

**Issue by BuchholzTim** [BuchholzTim/6-3-5-Brainwriter#7]
**Describe the bug**
It is possible to join a topic, which is already running/finished by using an old join-code.

**To Reproduce**
1. Go to 'Join Round'
2. Enter Correct but Old Join-Code

**Expected behavior**
- Message saying, that this topic no longer exists
- Show Results of Topic, if already finished

**Comment by MarcBollmann** [comment]
Inactive will be set if the moderator starts the game
